//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layton.AuditWizard.Administration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Layton.AuditWizard.Administration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap active {
            get {
                object obj = ResourceManager.GetObject("active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_user_corner {
            get {
                object obj = ResourceManager.GetObject("add_user_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_72 {
            get {
                object obj = ResourceManager.GetObject("Alert_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alert_create_corner {
            get {
                object obj = ResourceManager.GetObject("alert_create_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_trigger_32 {
            get {
                object obj = ResourceManager.GetObject("Alert_trigger_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alert_trigger_create_corner {
            get {
                object obj = ResourceManager.GetObject("alert_trigger_create_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alerts_32 {
            get {
                object obj = ResourceManager.GetObject("Alerts_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_16 {
            get {
                object obj = ResourceManager.GetObject("application_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_32 {
            get {
                object obj = ResourceManager.GetObject("application_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_addalias_corner {
            get {
                object obj = ResourceManager.GetObject("application_addalias_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_alias_32 {
            get {
                object obj = ResourceManager.GetObject("application_alias_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_alias_72 {
            get {
                object obj = ResourceManager.GetObject("application_alias_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_16 {
            get {
                object obj = ResourceManager.GetObject("application_license_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_32 {
            get {
                object obj = ResourceManager.GetObject("application_license_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_72 {
            get {
                object obj = ResourceManager.GetObject("application_license_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_corner {
            get {
                object obj = ResourceManager.GetObject("application_license_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_serial_32 {
            get {
                object obj = ResourceManager.GetObject("application_serial_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_serial_72 {
            get {
                object obj = ResourceManager.GetObject("application_serial_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_serial_number_corner {
            get {
                object obj = ResourceManager.GetObject("application_serial_number_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_settings_32 {
            get {
                object obj = ResourceManager.GetObject("application_settings_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_settings_72 {
            get {
                object obj = ResourceManager.GetObject("application_settings_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_settings_96 {
            get {
                object obj = ResourceManager.GetObject("application_settings_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_types_32 {
            get {
                object obj = ResourceManager.GetObject("asset_types_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_types_72 {
            get {
                object obj = ResourceManager.GetObject("asset_types_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_types_add_32 {
            get {
                object obj = ResourceManager.GetObject("asset_types_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_types_delete_32 {
            get {
                object obj = ResourceManager.GetObject("asset_types_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_types_edit_32 {
            get {
                object obj = ResourceManager.GetObject("asset_types_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap assettype_properties_corner {
            get {
                object obj = ResourceManager.GetObject("assettype_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_agent_72 {
            get {
                object obj = ResourceManager.GetObject("audit_agent_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_agent_corner {
            get {
                object obj = ResourceManager.GetObject("audit_agent_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_scanner_32 {
            get {
                object obj = ResourceManager.GetObject("audit_scanner_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_screendesigner_corner {
            get {
                object obj = ResourceManager.GetObject("audit_screendesigner_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_settings_32 {
            get {
                object obj = ResourceManager.GetObject("audit_settings_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_settings_ghosted_96 {
            get {
                object obj = ResourceManager.GetObject("audit_settings_ghosted_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap audit_upload_32 {
            get {
                object obj = ResourceManager.GetObject("audit_upload_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AuditAgent32 {
            get {
                object obj = ResourceManager.GetObject("AuditAgent32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AuditAgent321 {
            get {
                object obj = ResourceManager.GetObject("AuditAgent321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto_upload_corner {
            get {
                object obj = ResourceManager.GetObject("auto_upload_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aw_service_control_32 {
            get {
                object obj = ResourceManager.GetObject("aw_service_control_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aw_service_control_72 {
            get {
                object obj = ResourceManager.GetObject("aw_service_control_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aw_service_control_corner {
            get {
                object obj = ResourceManager.GetObject("aw_service_control_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer32 {
            get {
                object obj = ResourceManager.GetObject("computer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_list_32 {
            get {
                object obj = ResourceManager.GetObject("data_list_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_list_ghosted_96 {
            get {
                object obj = ResourceManager.GetObject("data_list_ghosted_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_32 {
            get {
                object obj = ResourceManager.GetObject("database_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_72 {
            get {
                object obj = ResourceManager.GetObject("database_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap datasetup_32 {
            get {
                object obj = ResourceManager.GetObject("datasetup_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_options_corner {
            get {
                object obj = ResourceManager.GetObject("email_options_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_service_control_corner {
            get {
                object obj = ResourceManager.GetObject("email_service_control_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_settings_72 {
            get {
                object obj = ResourceManager.GetObject("email_settings_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_settings_footer {
            get {
                object obj = ResourceManager.GetObject("email_settings_footer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email32 {
            get {
                object obj = ResourceManager.GetObject("email32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_locations_corner {
            get {
                object obj = ResourceManager.GetObject("export_locations_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesystem_settings_corner {
            get {
                object obj = ResourceManager.GetObject("filesystem_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ftp_settings_corner {
            get {
                object obj = ResourceManager.GetObject("ftp_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap general_setting_32 {
            get {
                object obj = ResourceManager.GetObject("general_setting_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap general_settings_ghosted_96 {
            get {
                object obj = ResourceManager.GetObject("general_settings_ghosted_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardware_settings_corner {
            get {
                object obj = ResourceManager.GetObject("hardware_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_picklists_corner {
            get {
                object obj = ResourceManager.GetObject("import_picklists_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_userdata_corner {
            get {
                object obj = ResourceManager.GetObject("import_userdata_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inport_locations_corner {
            get {
                object obj = ResourceManager.GetObject("inport_locations_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap internet_settings_corner {
            get {
                object obj = ResourceManager.GetObject("internet_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ipaddress_16 {
            get {
                object obj = ResourceManager.GetObject("ipaddress_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap load_scanner_32 {
            get {
                object obj = ResourceManager.GetObject("load_scanner_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap load_scanner_corner {
            get {
                object obj = ResourceManager.GetObject("load_scanner_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_16 {
            get {
                object obj = ResourceManager.GetObject("location_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_32 {
            get {
                object obj = ResourceManager.GetObject("location_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_72 {
            get {
                object obj = ResourceManager.GetObject("location_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_add_16 {
            get {
                object obj = ResourceManager.GetObject("location_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_add_32 {
            get {
                object obj = ResourceManager.GetObject("location_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_delete_16 {
            get {
                object obj = ResourceManager.GetObject("location_delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_delete_32 {
            get {
                object obj = ResourceManager.GetObject("location_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_edit_16 {
            get {
                object obj = ResourceManager.GetObject("location_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_edit_32 {
            get {
                object obj = ResourceManager.GetObject("location_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manage_license_types_corner {
            get {
                object obj = ResourceManager.GetObject("manage_license_types_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap missing_icon_32 {
            get {
                object obj = ResourceManager.GetObject("missing_icon_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mobiledevice_settings_corner {
            get {
                object obj = ResourceManager.GetObject("mobiledevice_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msi32 {
            get {
                object obj = ResourceManager.GetObject("msi32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notinstalled {
            get {
                object obj = ResourceManager.GetObject("notinstalled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_16 {
            get {
                object obj = ResourceManager.GetObject("pickitem_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_32 {
            get {
                object obj = ResourceManager.GetObject("pickitem_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_add_32 {
            get {
                object obj = ResourceManager.GetObject("pickitem_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_add_corner {
            get {
                object obj = ResourceManager.GetObject("pickitem_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_delete_32 {
            get {
                object obj = ResourceManager.GetObject("pickitem_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_edit_32 {
            get {
                object obj = ResourceManager.GetObject("pickitem_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pickitem_properties_corner {
            get {
                object obj = ResourceManager.GetObject("pickitem_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_16 {
            get {
                object obj = ResourceManager.GetObject("picklist_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_32 {
            get {
                object obj = ResourceManager.GetObject("picklist_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_48 {
            get {
                object obj = ResourceManager.GetObject("picklist_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_72 {
            get {
                object obj = ResourceManager.GetObject("picklist_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_add_corner {
            get {
                object obj = ResourceManager.GetObject("picklist_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_delete_32 {
            get {
                object obj = ResourceManager.GetObject("picklist_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_edit_32 {
            get {
                object obj = ResourceManager.GetObject("picklist_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picklist_properties_corner {
            get {
                object obj = ResourceManager.GetObject("picklist_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registry_settings_corner {
            get {
                object obj = ResourceManager.GetObject("registry_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registrykey_16 {
            get {
                object obj = ResourceManager.GetObject("registrykey_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_scanner_32 {
            get {
                object obj = ResourceManager.GetObject("save_scanner_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_scanner_corner {
            get {
                object obj = ResourceManager.GetObject("save_scanner_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_72 {
            get {
                object obj = ResourceManager.GetObject("scanner_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_deploy_email_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_deploy_email_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_deploy_network_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_deploy_network_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_new_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_new_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_shutdown_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_shutdown_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner_update_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_update_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_application_corner {
            get {
                object obj = ResourceManager.GetObject("select_application_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_assettype_properties_corner {
            get {
                object obj = ResourceManager.GetObject("select_assettype_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap software_settings_corner {
            get {
                object obj = ResourceManager.GetObject("software_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stopped {
            get {
                object obj = ResourceManager.GetObject("stopped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_32 {
            get {
                object obj = ResourceManager.GetObject("supplier_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_72 {
            get {
                object obj = ResourceManager.GetObject("supplier_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_add_32 {
            get {
                object obj = ResourceManager.GetObject("supplier_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_add_corner {
            get {
                object obj = ResourceManager.GetObject("supplier_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_delete_32 {
            get {
                object obj = ResourceManager.GetObject("supplier_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_edit_32 {
            get {
                object obj = ResourceManager.GetObject("supplier_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_edit_corner {
            get {
                object obj = ResourceManager.GetObject("supplier_edit_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbox_32 {
            get {
                object obj = ResourceManager.GetObject("Toolbox_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap top_grad_red {
            get {
                object obj = ResourceManager.GetObject("top_grad_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transparent {
            get {
                object obj = ResourceManager.GetObject("transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap udf_16 {
            get {
                object obj = ResourceManager.GetObject("udf_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap udf_32 {
            get {
                object obj = ResourceManager.GetObject("udf_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unavailable {
            get {
                object obj = ResourceManager.GetObject("unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_options_72 {
            get {
                object obj = ResourceManager.GetObject("upload_options_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_options_corner {
            get {
                object obj = ResourceManager.GetObject("upload_options_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usb_device_settings_corner {
            get {
                object obj = ResourceManager.GetObject("usb_device_settings_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_add_32 {
            get {
                object obj = ResourceManager.GetObject("user_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_add_corner {
            get {
                object obj = ResourceManager.GetObject("user_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_delete_32 {
            get {
                object obj = ResourceManager.GetObject("user_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_edit_32 {
            get {
                object obj = ResourceManager.GetObject("user_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradd_16 {
            get {
                object obj = ResourceManager.GetObject("useradd_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_110 {
            get {
                object obj = ResourceManager.GetObject("UserData_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_16 {
            get {
                object obj = ResourceManager.GetObject("UserData_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_32 {
            get {
                object obj = ResourceManager.GetObject("UserData_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_72 {
            get {
                object obj = ResourceManager.GetObject("UserData_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_applications_32 {
            get {
                object obj = ResourceManager.GetObject("UserData_applications_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserData_assets_32 {
            get {
                object obj = ResourceManager.GetObject("UserData_assets_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userdata_category_corner {
            get {
                object obj = ResourceManager.GetObject("userdata_category_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userdata_field_corner {
            get {
                object obj = ResourceManager.GetObject("userdata_field_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userdelete_16 {
            get {
                object obj = ResourceManager.GetObject("userdelete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userdetails_ghosted_128 {
            get {
                object obj = ResourceManager.GetObject("userdetails_ghosted_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useredit_16 {
            get {
                object obj = ResourceManager.GetObject("useredit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userlocations_corner {
            get {
                object obj = ResourceManager.GetObject("userlocations_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_32 {
            get {
                object obj = ResourceManager.GetObject("users_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_72 {
            get {
                object obj = ResourceManager.GetObject("users_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
