//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layton.AuditWizard.Applications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Layton.AuditWizard.Applications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Alert_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_32 {
            get {
                object obj = ResourceManager.GetObject("Alert_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_72 {
            get {
                object obj = ResourceManager.GetObject("Alert_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_active_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_active_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_delete_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_details_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_details_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alert_details_corner {
            get {
                object obj = ResourceManager.GetObject("alert_details_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alert_dismissed_16 {
            get {
                object obj = ResourceManager.GetObject("Alert_dismissed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alias_application_32 {
            get {
                object obj = ResourceManager.GetObject("alias_application_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alias_publisher_32 {
            get {
                object obj = ResourceManager.GetObject("alias_publisher_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_16 {
            get {
                object obj = ResourceManager.GetObject("application_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_32 {
            get {
                object obj = ResourceManager.GetObject("application_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_72 {
            get {
                object obj = ResourceManager.GetObject("application_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_add_16 {
            get {
                object obj = ResourceManager.GetObject("application_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_add_corner {
            get {
                object obj = ResourceManager.GetObject("application_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_alias_32 {
            get {
                object obj = ResourceManager.GetObject("application_alias_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_del_16 {
            get {
                object obj = ResourceManager.GetObject("application_del_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_global_properties_corner {
            get {
                object obj = ResourceManager.GetObject("application_global_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_hidden_16 {
            get {
                object obj = ResourceManager.GetObject("application_hidden_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_instance_72 {
            get {
                object obj = ResourceManager.GetObject("application_instance_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_instance_properties_corner {
            get {
                object obj = ResourceManager.GetObject("application_instance_properties_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_16 {
            get {
                object obj = ResourceManager.GetObject("application_license_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_32 {
            get {
                object obj = ResourceManager.GetObject("application_license_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_72 {
            get {
                object obj = ResourceManager.GetObject("application_license_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_96 {
            get {
                object obj = ResourceManager.GetObject("application_license_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_add_corner {
            get {
                object obj = ResourceManager.GetObject("application_license_add_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_license_edit_corner {
            get {
                object obj = ResourceManager.GetObject("application_license_edit_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_properties_16 {
            get {
                object obj = ResourceManager.GetObject("application_properties_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_properties_32 {
            get {
                object obj = ResourceManager.GetObject("application_properties_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_properties_72 {
            get {
                object obj = ResourceManager.GetObject("application_properties_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_properties_96 {
            get {
                object obj = ResourceManager.GetObject("application_properties_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_publisher_16 {
            get {
                object obj = ResourceManager.GetObject("application_publisher_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_publisher_72 {
            get {
                object obj = ResourceManager.GetObject("application_publisher_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_publisher_add_16 {
            get {
                object obj = ResourceManager.GetObject("application_publisher_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_serial_16 {
            get {
                object obj = ResourceManager.GetObject("application_serial_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_serial_32 {
            get {
                object obj = ResourceManager.GetObject("application_serial_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_view_16 {
            get {
                object obj = ResourceManager.GetObject("application_view_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_view_ghosted_96 {
            get {
                object obj = ResourceManager.GetObject("application_view_ghosted_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap approved_16 {
            get {
                object obj = ResourceManager.GetObject("approved_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer16 {
            get {
                object obj = ResourceManager.GetObject("computer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Documents_16 {
            get {
                object obj = ResourceManager.GetObject("Documents_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_action_corner {
            get {
                object obj = ResourceManager.GetObject("edit_action_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_action_corner1 {
            get {
                object obj = ResourceManager.GetObject("edit_action_corner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel_16 {
            get {
                object obj = ResourceManager.GetObject("excel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel_32 {
            get {
                object obj = ResourceManager.GetObject("excel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_16 {
            get {
                object obj = ResourceManager.GetObject("export_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_publishers_32 {
            get {
                object obj = ResourceManager.GetObject("filter_publishers_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_all_applications_32 {
            get {
                object obj = ResourceManager.GetObject("hide_all_applications_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_application_16 {
            get {
                object obj = ResourceManager.GetObject("hide_application_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_application_32 {
            get {
                object obj = ResourceManager.GetObject("hide_application_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hide_Computer_16 {
            get {
                object obj = ResourceManager.GetObject("Hide_Computer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hide_Computer_32 {
            get {
                object obj = ResourceManager.GetObject("Hide_Computer_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_add_16 {
            get {
                object obj = ResourceManager.GetObject("license_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_add_32 {
            get {
                object obj = ResourceManager.GetObject("license_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_delete_16 {
            get {
                object obj = ResourceManager.GetObject("license_delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_delete_32 {
            get {
                object obj = ResourceManager.GetObject("license_delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_edit_16 {
            get {
                object obj = ResourceManager.GetObject("license_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license_edit_32 {
            get {
                object obj = ResourceManager.GetObject("license_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manage_license_types_corner {
            get {
                object obj = ResourceManager.GetObject("manage_license_types_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap not_approved_16 {
            get {
                object obj = ResourceManager.GetObject("not_approved_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notes_16 {
            get {
                object obj = ResourceManager.GetObject("notes_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap os_16 {
            get {
                object obj = ResourceManager.GetObject("os_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap os_96 {
            get {
                object obj = ResourceManager.GetObject("os_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf_32 {
            get {
                object obj = ResourceManager.GetObject("pdf_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_application_corner {
            get {
                object obj = ResourceManager.GetObject("select_application_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_all_applications_32 {
            get {
                object obj = ResourceManager.GetObject("show_all_applications_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_application_16 {
            get {
                object obj = ResourceManager.GetObject("show_application_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_application_32 {
            get {
                object obj = ResourceManager.GetObject("show_application_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_32 {
            get {
                object obj = ResourceManager.GetObject("supplier_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap support_contract_32 {
            get {
                object obj = ResourceManager.GetObject("support_contract_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_16 {
            get {
                object obj = ResourceManager.GetObject("view_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xps_16 {
            get {
                object obj = ResourceManager.GetObject("xps_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xps_32 {
            get {
                object obj = ResourceManager.GetObject("xps_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
