--------------------------------------------------------------------------
--																		--
-- AuditWizard Create Tables											--
-- ===========================											--
--																		--
--------------------------------------------------------------------------
--																		--
-- Description															--
-- ===========															--
--																		--
-- This procedure is part of the AuditWizard Product					--
-- It is used to create the tables within the database					--
--																		--
--------------------------------------------------------------------------
--																		--
-- History																--
-- =======																--
--																		--
--	11-FEB-2008			Chris Drew		Initial Version					--
--																		--
--------------------------------------------------------------------------

--USE [AuditWizard]
    
---
---    ACTIONS TABLE
---
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ACTIONS](
	[_ACTIONID] [int] IDENTITY(1,1) NOT NULL,
	[_TYPE] [int] NOT NULL CONSTRAINT [DF_ACTIONS__ACTION_TYPE]  DEFAULT ((0)),
	[_APPLICATIONID] [int] NOT NULL CONSTRAINT [DF_ACTIONS__APPLICATIONID]  DEFAULT ((0)),
	[_STATUS] [int] NOT NULL CONSTRAINT [DF_ACTIONS__STATUS]  DEFAULT ((0)),
	[_ASSETS] [varchar](5000) NOT NULL CONSTRAINT [DF_ACTIONS__ASSETS]  DEFAULT (''),
	[_NOTES] [varchar](1020) NOT NULL CONSTRAINT [DF_ACTIONS__NOTES]  DEFAULT (''),
) ON [PRIMARY]




  
---
---    ALERTS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[ALERTS](
	[_ALERTID] [int] IDENTITY(1,1) NOT NULL,
	[_TYPE] [int] NOT NULL DEFAULT ((0)),
	[_CATEGORY] [int] NOT NULL DEFAULT ((0)),
	[_MESSAGE] [varchar](510) NOT NULL DEFAULT (''),
	[_FiELD1] [varchar](1020) NOT NULL DEFAULT (''),
	[_FIELD2] [varchar](1020) NOT NULL DEFAULT (''),
	[_STATUS] [int] NOT NULL DEFAULT ((0)),
	[_ALERTDATE] [datetime] NOT NULL,
	[_ASSETNAME] [varchar](255) NOT NULL DEFAULT (''),
	[_ALERTNAME] [varchar](255) NOT NULL DEFAULT (''),
 CONSTRAINT [PK_ALERTS] PRIMARY KEY CLUSTERED 
(
	[_ALERTID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




  
---
---    APPLICATIONS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[APPLICATIONS](
	[_APPLICATIONID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME] [varchar](255) NOT NULL,
	[_VERSION] [varchar](255) NOT NULL DEFAULT (''),
	[_PUBLISHER] [varchar](255) NOT NULL DEFAULT ('<unknown>'),
	[_GUID] [varchar](255) NOT NULL DEFAULT (''),
	[_IGNORED] [bit] NOT NULL DEFAULT ((0)),
	[_ISOS] [bit] NOT NULL DEFAULT ((0)),
	[_ALIASED_TOID] [int] NOT NULL DEFAULT ((0)),
	[_ASSIGNED_FILEID] [int] NOT NULL DEFAULT ((0)),
	[_USER_DEFINED] [bit] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_APPLICATIONS] PRIMARY KEY CLUSTERED 
(
	[_APPLICATIONID] ASC
) ON [PRIMARY]
) ON [PRIMARY]

  


  
---
---    APPLICATION_INSTANCES TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[APPLICATION_INSTANCES](
	[_INSTANCEID] [int] IDENTITY(1,1) NOT NULL,
	[_APPLICATIONID] [int] NOT NULL,
	[_BASE_APPLICATIONID] [int] NOT NULL DEFAULT ((0)),
	[_ASSETID] [int] NOT NULL,
	[_PRODUCTID] [varchar](255) NOT NULL DEFAULT (''),
	[_CDKEY] [varchar](255) NOT NULL DEFAULT (''),
	[_SUPPORTED] [bit] NOT NULL DEFAULT ((0)),
	[_SUPPORT_EXPIRY] [datetime] NULL,
	[_SUPPORT_ALERTDAYS] [int] NOT NULL DEFAULT ((-1)),
	[_SUPPORT_ALERTEMAIL] [bit] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_APPLICATION_INSTANCES] PRIMARY KEY CLUSTERED 
(
	[_INSTANCEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


---    Additional Index
CREATE NONCLUSTERED INDEX [ind_APPLICATION_INSTANCES_ASSETID] ON [dbo].[APPLICATION_INSTANCES] ([_ASSETID]ASC )

  

---
---    AUDITEDITEMS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[AUDITEDITEMS](
	[_AUDITEDITEMID] [int] IDENTITY(1,1) NOT NULL,
	[_ASSETID]		[int]			NOT NULL,
	[_CATEGORY]		[varchar](900) NOT NULL DEFAULT (''),
	[_NAME]			[varchar](1024) NOT NULL DEFAULT (''),
	[_VALUE]		[varchar](1024) NOT NULL DEFAULT (''),
	[_DISPLAY_UNITS] [varchar](32)	NOT NULL DEFAULT (''),
	[_DATATYPE]		[int]			NOT NULL DEFAULT ((0)),
	[_HISTORIED]	[bit]			NOT NULL DEFAULT ((1)),
	[_GROUPED]		[bit]			NOT NULL DEFAULT ((0)),
	[_ICON]			[varchar](255)	NOT NULL DEFAULT (''),
 CONSTRAINT [PK_AUDITEDITEMS] PRIMARY KEY CLUSTERED 
(
	[_AUDITEDITEMID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


---    Additional Index
CREATE NONCLUSTERED INDEX [ind_AUDITEDITEMS_CATEGORY] ON [dbo].[AUDITEDITEMS] ([_CATEGORY]ASC )
CREATE NONCLUSTERED INDEX [ind_AUDITEDITEMS_ASSETID] ON [dbo].[AUDITEDITEMS] ([_ASSETID]ASC )
  
  
---
---    AUDITTRAIL TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[AUDITTRAIL]
(
	[_AUDITTRAILID] [int] IDENTITY(1,1) NOT NULL,
	[_ASSETID] [int] NOT NULL DEFAULT ((0)),
	[_USERNAME] [varchar](255) NOT NULL DEFAULT (''),
	[_DATE] [datetime] NOT NULL DEFAULT (''),
	[_CLASS] [int] NOT NULL DEFAULT ((0)),
	[_TYPE] [int] NOT NULL DEFAULT ((0)),
	[_KEY] [varchar](255) NOT NULL DEFAULT (''),
	[_VALUE1] [varchar](255) NOT NULL DEFAULT (''),
	[_VALUE2] [varchar](255) NOT NULL DEFAULT (''),
 CONSTRAINT [PK_AUDITTRAIL] PRIMARY KEY CLUSTERED 
(
	[_AUDITTRAILID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


---    Additional Index
CREATE NONCLUSTERED INDEX [ind_AUDITTRAIL_ASSETID] ON [dbo].[AUDITTRAIL] ([_ASSETID]ASC )



 
---
---    ASSETS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[ASSETS](
	[_ASSETID] [int] IDENTITY(1,1) NOT NULL,
	[_UNIQUEID] [varchar](255) NOT NULL,
	[_NAME] [varchar](255) NOT NULL,
	[_LOCATIONID] [int] NOT NULL CONSTRAINT [DF_ASSETS__LOCATIONID]  DEFAULT ((1)),
	[_DOMAINID] [int] NOT NULL DEFAULT (''),
	[_PARENT_ASSETID] [int] NOT NULL DEFAULT ((0)),
	[_IPADDRESS] [varchar](16) NOT NULL DEFAULT ((1)),
	[_MACADDRESS] [varchar](32) NOT NULL DEFAULT (''),
	[_LASTAUDIT] [datetime] NULL,
	[_HIDDEN] [bit] NOT NULL DEFAULT ((0)),
	[_REQUESTAUDIT] [bit] NOT NULL DEFAULT ((0)),
	[_AGENT_STATUS] [int] NOT NULL DEFAULT ((0)),
	[_ASSETTYPEID] [int] NOT NULL DEFAULT 2,
	[_MAKE] [varchar](255) NOT NULL DEFAULT (''),
	[_MODEL] [varchar](255) NOT NULL DEFAULT (''),
	[_SERIAL_NUMBER] [varchar](255) NOT NULL DEFAULT (''),
	[_SUPPLIERID] [int] NOT NULL CONSTRAINT [DF_LICENSES__SUPPLIERID]  DEFAULT ((1)),
	[_STOCK_STATUS] [int] NOT NULL DEFAULT((0)),
	[_AGENT_VERSION] [varchar](32) NOT NULL DEFAULT (''),
	[_ALERTS_ENABLED] [bit] NOT NULL DEFAULT ((1)),
	[_OVERWRITEDATA] [bit] NOT NULL DEFAULT ((1)),
	[_ASSETTAG] [varchar](255) NULL DEFAULT (''),
 CONSTRAINT [PK_ASSETS] PRIMARY KEY CLUSTERED 
(
	[_ASSETID] ASC
) ON [PRIMARY]
) ON [PRIMARY]





---
---    ASSET_TYPES Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[ASSET_TYPES]
(
	[_ASSETTYPEID] 	[int] IDENTITY(1,1) NOT NULL,
	[_NAME] 		[varchar](255) 		NOT NULL DEFAULT (''),
	[_PARENTID] 	[int] 				NULL,
	[_AUDITABLE]	[bit]				NOT NULL DEFAULT ((0)),
	[_INTERNAL]		[bit]				NOT NULL DEFAULT ((0)),
	[_ICON] 		[varchar](255) 		NOT NULL DEFAULT (''),
 CONSTRAINT [PK_ASSET_TYPES] PRIMARY KEY CLUSTERED 
(
	[_ASSETTYPEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]



---
---    DOCUMENTS Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[DOCUMENTS](
	[_DOCUMENTID] [int] IDENTITY(1,1) NOT NULL,
	[_PATH] [varchar](255) NOT NULL DEFAULT (''),
	[_NAME] [varchar](255) NOT NULL DEFAULT (''),
	[_SCOPE] [int] NOT NULL DEFAULT ((0)),
	[_PARENTID] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_DOCUMENTS] PRIMARY KEY CLUSTERED 
(
	[_DOCUMENTID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




---
---    DOMAINS Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[DOMAINS](
	[_DOMAINID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME]		[varchar](255)		NOT NULL DEFAULT (''),
	[_PARENTID] [int] 				NULL,
	[_HIDDEN]	[bit]				NOT NULL DEFAULT ((0))
) ON [PRIMARY]








---
---	   FS_FILES TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[FS_FILES]
(
	[_FILEID]		[int] IDENTITY(1,1) NOT NULL,
	[_PARENTID]		[int]			NOT NULL	DEFAULT ((0)),
	[_NAME]			[varchar](255)	NOT NULL	DEFAULT (''),
	[_ASSETID]		[int]			NOT NULL	DEFAULT ((0)),
	[_SIZE]			[int]			NOT NULL	DEFAULT ((0)),
	[_CREATED_DATE] [datetime]		NULL		DEFAULT ((0)),
	[_MODIFIED_DATE] [datetime]		NULL		DEFAULT ((0)),
	[_LASTACCESSED_DATE] [datetime] NULL,
	[_PUBLISHER]	[varchar](255)	NOT NULL	DEFAULT (''),
	[_PRODUCTNAME]	[varchar](255)	NOT NULL	DEFAULT (''),
	[_DESCRIPTION]	[varchar](255)	NOT NULL	DEFAULT (''),
	[_PRODUCT_VERSION1] [varchar](255) NOT NULL DEFAULT (''),
	[_PRODUCT_VERSION2] [varchar](255) NOT NULL DEFAULT (''),
	[_FILE_VERSION1] [varchar](255) NOT NULL	DEFAULT (''),
	[_FILE_VERSION2] [varchar](255) NOT NULL	DEFAULT (''),
	[_ORIGINAL_FILENAME] [varchar](255) NOT NULL DEFAULT (''),
	[_ASSIGN_APPLICATIONID] [int]	NOT NULL	DEFAULT ((0)),
CONSTRAINT [PK_FS_FILES] PRIMARY KEY CLUSTERED 
(
	[_FILEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF


---    Additional Index
CREATE NONCLUSTERED INDEX [ind_FS_FILES_ASSETID] ON [dbo].[FS_FILES] ([_ASSETID]ASC )





---
---	   FS_FOLDERS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[FS_FOLDERS]
(
	[_FOLDERID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME] [varchar](255) DEFAULT (''),
	[_PARENTID] [int] NOT NULL DEFAULT ((0)),
	[_ASSETID] [int] NOT NULL DEFAULT ((0)),
CONSTRAINT [PK_FS_FOLDERS] PRIMARY KEY CLUSTERED 
(
	[_FOLDERID] ASC
) ON [PRIMARY]
) ON [PRIMARY]



---    Additional Index
CREATE NONCLUSTERED INDEX [ind_FS_FOLDERS_ASSETID] ON [dbo].[FS_FOLDERS] ([_ASSETID]ASC )




---
---    LICENSES TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[LICENSES](
	[_LICENSEID] [int] IDENTITY(1,1) NOT NULL,
	[_LICENSETYPEID] [int] NULL,
	[_APPLICATIONID] [int] NOT NULL DEFAULT ((0)),
	[_COUNT] [int] NOT NULL DEFAULT ((0)),
	[_SUPPORTED] [bit] NOT NULL DEFAULT ((0)),
	[_SUPPORT_EXPIRES] [datetime] NULL,
	[_SUPPORT_ALERTDAYS] [int] NOT NULL  DEFAULT ((7)),
	[_SUPPORT_ALERTBYEMAIL] [bit] NOT NULL DEFAULT ((0)),
	[_SUPPORT_ALERTRECIPIENTS] [varchar](1020) NOT NULL DEFAULT (''),
	[_SUPPLIERID] [int] NOT NULL DEFAULT ((1)),
 CONSTRAINT [PK_LICENSES] PRIMARY KEY CLUSTERED 
(
	[_LICENSEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




  
---
---    LICENSE_TYPES TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[LICENSE_TYPES](
	[_LICENSETYPEID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME] [varchar](255) NULL,
	[_COUNTED] [bit] NULL DEFAULT ((0)),
 CONSTRAINT [PK_LICENSE_TYPES] PRIMARY KEY CLUSTERED 
(
	[_LICENSETYPEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]



  
---
---    LOCATIONS TABLE
---   
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[LOCATIONS]
(
	[_LOCATIONID] 		[int] IDENTITY(1,1) NOT NULL,
	[_FULLNAME] 		[varchar](1024) 	NOT NULL,
	[_NAME] 			[varchar](255) 		NOT NULL,
	[_PARENTID] 		[int] 				NULL,
	[_START_IPADDRESS] 	[varchar](510) 		NOT NULL DEFAULT (''),
	[_END_IPADDRESS] 	[varchar](510) 		NOT NULL DEFAULT (''),
	[_HIDDEN]			[bit]				NOT NULL DEFAULT ((0))
CONSTRAINT [PK_LOCATIONS] PRIMARY KEY CLUSTERED 
(
	[_LOCATIONID] ASC
) ON [PRIMARY]
) ON [PRIMARY]



---
---    NOTES Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[NOTES]
(
	[_NOTEID] [int] IDENTITY(1,1) NOT NULL,
	[_DATE] [datetime] NOT NULL DEFAULT (''),
	[_SCOPE] [int] NOT NULL DEFAULT ((0)),
	[_PARENTID] [int] NOT NULL DEFAULT ((0)),
	[_USER] [varchar](255) NOT NULL DEFAULT (''),
	[_TEXT] [varchar](4000) NOT NULL DEFAULT ('')
CONSTRAINT [PK_NOTES] PRIMARY KEY CLUSTERED 
(
	[_NOTEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




---
---    OPERATIONS Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[OPERATIONS](
	[_OPERATIONID]	[int] IDENTITY(1,1) NOT NULL,
	[_OPERATION]	[int]			NOT NULL DEFAULT ((0)),
	[_START_DATE]	[datetime]		NULL,
	[_END_DATE]		[datetime]		NULL,
	[_ASSETID]		[int]			NOT NULL DEFAULT ((0)),
	[_STATUS]		[int]			NOT NULL DEFAULT ((0)),
	[_ERRORTEXT]	[varchar](510)	NOT NULL DEFAULT (''),
CONSTRAINT [PK_OPERATIONS] PRIMARY KEY CLUSTERED 
(
	[_OPERATIONID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF


---
---    PICKLISTS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[PICKLISTS]
(
	[_PICKLISTID] 	[int] IDENTITY(1,1) NOT NULL,
	[_NAME] 		[varchar](255) 		NOT NULL 	DEFAULT (''),
	[_PARENTID] 	[int] 						 	DEFAULT (NULL),
CONSTRAINT [PK_PICKLISTS] PRIMARY KEY CLUSTERED 
(
	[_PICKLISTID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




  
---
---    SETTINGS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[SETTINGS](
	[_SETTINGID] [int] IDENTITY(1,1) NOT NULL,
	[_KEY] [varchar](255) NOT NULL DEFAULT (''),
	[_VALUE] [varchar](255) NOT NULL DEFAULT ('')
) ON [PRIMARY]




---
--- SCANNERS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[SCANNERS](
	[_SCANNERID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME] [varchar](255) NOT NULL,
	[_XML] [text] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


  
---
---    SUPPLIERS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[SUPPLIERS](
	[_SUPPLIERID] [int] IDENTITY(1,1) NOT NULL,
	[_NAME] [varchar](255) NOT NULL DEFAULT (''),
	[_ADDRESS1] [varchar](255) NOT NULL DEFAULT (''),
	[_ADDRESS2] [varchar](255) NOT NULL DEFAULT (''),
	[_CITY] [varchar](255) NOT NULL DEFAULT (''),
	[_STATE] [varchar](255) NOT NULL DEFAULT (''),
	[_ZIP] [varchar](64) NOT NULL DEFAULT (''),
	[_TELEPHONE] [varchar](64) NOT NULL DEFAULT (''),
	[_CONTACT_NAME] [varchar](255) NOT NULL DEFAULT (''),
	[_CONTACT_EMAIL] [varchar](255) NOT NULL DEFAULT (''),
	[_WWW] [varchar](255) NOT NULL DEFAULT (''),
	[_FAX] [varchar](255) NOT NULL DEFAULT (''),
	[_NOTES] [varchar](1020) NOT NULL DEFAULT (''),
 CONSTRAINT [PK_SUPPLIERS] PRIMARY KEY CLUSTERED 
(
	[_SUPPLIERID] ASC
) ON [PRIMARY]
) ON [PRIMARY]



  
---
---    USERS TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[USERS](
	[_USERID] [int] IDENTITY(1,1) NOT NULL,
	[_LOGIN] [varchar](255) NOT NULL DEFAULT (''),
	[_PASSWORD] [varchar](255) NOT NULL DEFAULT (''),
	[_FIRSTNAME] [varchar](255) NOT NULL DEFAULT (''),
	[_LASTNAME] [varchar](255) NOT NULL DEFAULT (''),
	[_ACCESSLEVEL] [int] NOT NULL DEFAULT ((0)),
	[_ROOTLOCATION] [int] NOT NULL DEFAULT ((1)),
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[_USERID] ASC
) ON [PRIMARY]
) ON [PRIMARY]






---
---   USERDATA_DEFINITIONS Table
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[USERDATA_DEFINITIONS]
(
	[_USERDEFID] 	[int] IDENTITY(1,1) NOT NULL,
	[_NAME] 		[varchar](255) 	NOT NULL DEFAULT (''),
	[_PARENTID] 	[int] 			NULL,
	[_ISMANDATORY] 	[bit] 			NOT NULL DEFAULT ((0)),
	[_TYPE] 		[int] 			NOT NULL DEFAULT ((0)),
	[_TABORDER] 	[int] 			NOT NULL DEFAULT ((0)),
	[_APPLIESTO] 	[int]			NOT NULL DEFAULT ((0)),
	[_VALUE1] 		[varchar](255) 	NOT NULL DEFAULT (''),
	[_VALUE2] 		[varchar](255) 	NOT NULL DEFAULT (''),
	[_ICON] 		[varchar](255) 	NOT NULL DEFAULT (''),
	[_SCOPE]		[int] 			NOT NULL DEFAULT ((0)),
CONSTRAINT [PK_USERDATA_DEFINITIONS] PRIMARY KEY CLUSTERED 
(
	[_USERDEFID] ASC
) ON [PRIMARY]
) ON [PRIMARY]




SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[USERDATA_VALUES]
(
	[_USERVALUEID] 	[int] IDENTITY(1,1) NOT NULL,
	[_USERDEFID] 	[int] 			NOT NULL DEFAULT ((0)),
	[_PARENTTYPE] 	[int] 			NOT NULL DEFAULT ((0)),
	[_PARENTID] 	[int] 			NOT NULL,
	[_VALUE] 		[varchar](1020) NOT NULL DEFAULT (''),
CONSTRAINT [PK_USERDATA_VALUES] PRIMARY KEY CLUSTERED 
(
	[_USERVALUEID] ASC
) ON [PRIMARY]
) ON [PRIMARY]


  
---
---    VERSION TABLE
---
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[VERSION](
	[_TITLE] [varchar](255) NOT NULL DEFAULT (''),
	[_MAJOR] [int] NOT NULL DEFAULT ((0)),
	[_MINOR] [int] NOT NULL DEFAULT ((0)),
	[_DATE] [datetime] NOT NULL DEFAULT (''),
	[_SQLVER] [varchar](255) NOT NULL DEFAULT (''),
	[_USER] [varchar](255) NOT NULL DEFAULT (''),
	[_PASSWORD] [varchar](255) NOT NULL DEFAULT ('admin')
) ON [PRIMARY]



