DELETE FROM [dbo].[VERSION];
DELETE FROM [dbo].[USERDATA_VALUES];
DELETE FROM [dbo].[USERS];
DELETE FROM [dbo].[USERDATA_DEFINITIONS];
DELETE FROM [dbo].[SCANNERS];
DELETE FROM [dbo].[SETTINGS];
DELETE FROM [dbo].[PICKLISTS];
DELETE FROM [dbo].[OPERATIONS];
DELETE FROM [dbo].[NOTES];
DELETE FROM [dbo].[LOCATIONS];
DELETE FROM [dbo].[FS_FOLDERS];
DELETE FROM [dbo].[FS_FILES];
DELETE FROM [dbo].[DOMAINS];
DELETE FROM [dbo].[AUDITTRAIL];
DELETE FROM [dbo].[AUDITEDITEMS];
DELETE FROM [dbo].[DOCUMENTS];
DELETE FROM [dbo].[ALERTS];
DELETE FROM [dbo].[LICENSES];
DELETE FROM [dbo].[LICENSE_TYPES];
DELETE FROM [dbo].[SUPPLIERS];
DELETE FROM [dbo].[ACTIONS];
DELETE FROM [dbo].[APPLICATION_INSTANCES];
DELETE FROM [dbo].[APPLICATIONS];
DELETE FROM [dbo].[ASSETS];
DELETE FROM [dbo].[ASSET_TYPES];














