ALTER TABLE AUDITEDITEMS
drop CONSTRAINT PK__AUDITEDITEMS__0000000000000623
--Qstart--
ALTER TABLE AUDITEDITEMS
ALTER COLUMN _AUDITEDITEMID BigInt
--Qstart--
ALTER TABLE AUDITEDITEMS
ADD CONSTRAINT PK__AUDITEDITEMS__0000000000000623 PRIMARY KEY (_AUDITEDITEMID)
--Qstart--
ALTER TABLE VERSION
ADD _REVISION int;
--Qstart--
ALTER TABLE VERSION
ADD _PATCHVERSIONCHANGED int;
--Qstart--
UPDATE VERSION
   SET _MAJOR = 8
      ,_MINOR = 4
      ,_REVISION = 5
	  ,_PATCHVERSIONCHANGED = 1
 WHERE _TITLE ='AuditWizard Database'




